In [ ]:
%pip install databricks
%pip install databricks-sql-connector

In [60]:
from databricks import sql

import pandas as pd
import os

connection = sql.connect(
                        server_hostname = "xxx",
                        http_path = "xxx",
                        access_token = "xxx")

cursor = connection.cursor()

cursor.execute("select * from flight_delta.FlightDeltaLake limit 10 ")



result = cursor.fetchall()

type(result)

#print(result)

df = pd.DataFrame(data=result)
                  
df = pd.DataFrame(data=result, columns = ['Year','Month','DayofMonth','DayOfWeek','DepTime','CRSDepTime','ArrTime','CRSArrTime','UniqueCarrier','FlightNum','TailNum','ActualElapsedTime','CRSElapsedTime','AirTime','ArrDelay','DepDelay','Origin','Dest','Distance','TaxiIn','TaxiOut','Cancelled','CancellationCode','Diverted','CarrierDelay','WeatherDelay','NASDelay','SecurityDelay','LateAircraftDelay','IsArrDelayed','IsDepDelayed'])

cursor.close()
connection.close()

In [61]:
df

,Year,Month,DayofMonth,DayOfWeek,DepTime,CRSDepTime,ArrTime,CRSArrTime,UniqueCarrier,FlightNum,...,Cancelled,CancellationCode,Diverted,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay,IsArrDelayed,IsDepDelayed
0,1987,10,14,3,741,730,912,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,YES
1,1987,10,15,4,729,730,903,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,NO
2,1987,10,17,6,741,730,918,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,YES
3,1987,10,18,7,729,730,847,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,NO,NO
4,1987,10,19,1,749,730,922,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,YES
5,1987,10,21,3,728,730,848,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,NO,NO
6,1987,10,22,4,728,730,852,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,NO
7,1987,10,23,5,731,730,902,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,YES
8,1987,10,24,6,744,730,908,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,YES
9,1987,10,25,7,729,730,851,849,PS,1451,...,0,NA,0,NA,NA,NA,NA,NA,YES,NO